version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT"

  mesos-master:
    image: mesosphere/mesos-master:1.5.2
    container_name: mesos-master
    privileged: true
    environment:
      - MESOS_HOSTNAME=$HOST_IP
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
    depends_on:
      - zookeeper
    ports:
      - "5050:5050"
    healthcheck:
      test: "curl -f http://localhost:5050/health || exit 1"

  mesos-slave:
    image: mesosphere/mesos-slave:1.5.2
    container_name: mesos-slave
    pid: "host"
    privileged: true
    environment:
      - MESOS_HOSTNAME=$HOST_IP
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    depends_on:
      - zookeeper
      - mesos-master
    ports:
      - "5151:5151"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.5.15
    container_name: marathon
    environment:
      - MARATHON_HOSTNAME=$HOST_IP
      - MARATHON_HTTP_PORT=8090
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/marathon
    depends_on:
      - zookeeper
      - mesos-master
    ports:
      - "8090:8090"

  mysql:
    image: mysql:5.7.37
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"
